---
title: "Actividad 3"
author: "Grupo 22"
date: "2026-01-22"
output: html_document
---

```{r, warning=FALSE}
#Install libraries
#install.packages(c("factoextra", "nortest", "gtsummary","pheatmap")
#Libraries
library(ggplot2)
library(dplyr)
library(nortest)
library(stats)
library(car)
library(gtsummary)
library(tidyverse)
library(factoextra)
library(gridExtra)
library(pheatmap)
library(pROC)
file <- ("./Base de datos Los Simpson completa.csv")
df <- read.csv(file, stringsAsFactors = FALSE)

```
#Limpieza de datos
```{r, warning=FALSE}
genes_interes <-names(df)[
  match("ADCY3", names(df)) :
  match("UHMK1", names(df))
]
genes_interes

```

```{r, warning=FALSE}
NA_gen<-sapply(df[, genes_interes], function(x) sum(is.na(x)))
NA_gen

```


#Normalidad

```{r, warning=FALSE}
prueba_shapiro<- lapply(genes_interes, function(g) {
  
  x <- as.numeric(df[[g]])
  
  if (length(na.omit(x)) < 3 || sd(x, na.rm = TRUE) == 0) {
    return(data.frame(
      gene = g,
      W = NA,
      p_value = NA
    ))
  }
  
  test <- shapiro.test(x)
  
  data.frame(
    gene = g,
    W = test$statistic,
    p_value = test$p.value
  )
})

shapiro_table <- bind_rows(prueba_shapiro) %>%
  mutate(
    normalidad = ifelse(p_value >= 0.05,
                        "Normalidad",
                        "No normalidad")
  ) %>%
  arrange(p_value)
shapiro_table
```

```{r, warning=FALSE}
# ------------------------------------------------------------------
# 3.1 Preparación de datos para PCA
# ------------------------------------------------------------------

genes_pca <- df[, genes_interes]

# Verificar que no haya NA 
sum(is.na(genes_pca))

# Centrar y escalar las variables antes de PCA
genes_pca_scaled <- scale(genes_pca, center = TRUE, scale = TRUE)

# ------------------------------------------------------------------
# 3.2 Ejecutar el PCA
# ------------------------------------------------------------------

# Realizar PCA 
pca_result <- prcomp(genes_pca_scaled, center = FALSE, scale. = FALSE)


# ------------------------------------------------------------------
# 3.3 Extraer los scores de las primeras 6 componentes principales
# ------------------------------------------------------------------

# Obtener los scores 
pca_scores <- as.data.frame(pca_result$x[, 1:6])

# Renombrar las columnas
colnames(pca_scores) <- paste0("PC", 1:6)

# Agregar los scores al dataframe original
df <- cbind(df, pca_scores)

# Verificar que se agregaron correctamente
head(df[, c("nombre", "PC1", "PC2", "PC3", "PC4", "PC5", "PC6")])

# ------------------------------------------------------------------
# 3.4 Crear tablas de resumen del PCA
# ------------------------------------------------------------------

# TABLA 1: Varianza explicada por cada componente (R²)
varianza_explicada <- data.frame(
  Componente = paste0("PC", 1:length(pca_result$sdev)),
  Desviacion_Estandar = pca_result$sdev,
  Varianza = pca_result$sdev^2,
  Proporcion_Varianza = (pca_result$sdev^2) / sum(pca_result$sdev^2),
  Varianza_Acumulada = cumsum((pca_result$sdev^2) / sum(pca_result$sdev^2))
) %>%
  mutate(
    R_cuadrado = Proporcion_Varianza * 100,
    R_cuadrado_acumulado = Varianza_Acumulada * 100
  )

# Mostrar solo las primeras 6 componentes
tabla_varianza <- varianza_explicada[1:6, c("Componente", "R_cuadrado", "R_cuadrado_acumulado")]
print(tabla_varianza)

# TABLA 2: Cargas de las variables en los componentes principales
cargas_pca <- as.data.frame(pca_result$rotation[, 1:6])
cargas_pca <- round(cargas_pca, 3)
cargas_pca <- cbind(Variable = rownames(cargas_pca), cargas_pca)
rownames(cargas_pca) <- NULL

# Mostrar primeras filas
head(cargas_pca, 10)
```


```{r, warning=FALSE}
# ------------------------------------------------------------------
# 4.Visualizaciones
# ------------------------------------------------------------------
#Mapa de variables 
fviz_pca_var(pca_result,
             col.var = "cos2",
             gradient.cols = c("blue", "yellow", "red"),
             repel = TRUE,
             title = "Variables - Calidad de representación (cos2)")
#Contribucion de las variables
var_coords <- get_pca_var(pca_result)$coord
set.seed(123)
km_vars <- kmeans(var_coords, centers = 3)
grupo_vars <- as.factor(km_vars$cluster)
fviz_pca_var(pca_result, 
             col.var = grupo_vars, 
             palette = "jco", 
             legend.title = "Cluster Genes",
             repel = TRUE,
             title = "Clustering de Variables (Genes)")
# Contribución a la Dimensión 1 (PC1)
p1 <- fviz_contrib(pca_result, choice = "var", axes = 1, top = 10, title = "Contribución a PC1")
# Contribución a la Dimensión 2 (PC2)
p2 <- fviz_contrib(pca_result, choice = "var", axes = 2, top = 10, title = "Contribución a PC2")

# Mostrar ambos gráficos 

grid.arrange(p1, p2, ncol = 2)

# Criterio escogido: <25 Normal, 25-30 Sobrepeso, >30 Obesidad
df <- df %>%
  mutate(categoria_imc = case_when(
    imc_kg_m2 < 25 ~ "Normal",
    imc_kg_m2 >= 25 & imc_kg_m2 < 30 ~ "Sobrepeso",
    imc_kg_m2 >= 30 ~ "Obesidad",
    TRUE ~ "Desconocido"
  ))

# Individuos
fviz_pca_ind(pca_result,
             geom.ind = "point", 
             col.ind = df$categoria_imc, 
             palette = c("#00AFBB", "#E7B800", "#FC4E07"), 
             addEllipses = TRUE, 
             legend.title = "IMC",
             title = "Individuos por Categoría de IMC")

#Clustering de individuos
# Calculo de los  K-means sobre los individuos (usando los resultados del PCA)
set.seed(123)
km_ind <- kmeans(pca_result$x, centers = 3)

#Visualizacion
fviz_cluster(km_ind, 
             data = genes_pca_scaled, 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_minimal(),
             title = "Clustering de Individuos (Basado en PCA)")
```

```{r, warning=FALSE}
# ------------------------------------------------------------------
# 5. Correlaciones de Spearman: genes vs PCA
# ------------------------------------------------------------------

# Correlaciones Spearman
cor_spearman <- cor(
  genes_pca,
  pca_scores,
  method = "spearman",
  use = "pairwise.complete.obs"
)

# ------------------------------------------------------------------
# 5. Heatmap: genes vs PCA
# ------------------------------------------------------------------

## Heatmap usando pheatmap
pheatmap(
  cor_spearman,
  color = colorRampPalette(c("skyblue", "white", "pink"))(100),
  clustering_distance_rows = "euclidean",
  clustering_distance_cols = "euclidean",
  clustering_method = "ward.D2",
  scale = "none",
  fontsize_row = 6,
  fontsize_col = 10,
  main = "Heatmap de correlaciones Spearman (Genes vs 6 PCs)"
)

## Heatmap usando datos crudos
pheatmap(
  genes_pca_scaled,
  fontsize_col = 6,
  color = colorRampPalette(c("green", "white", "orange"))(100),
  main = "Heatmap de expresión génica (datos escalados)"
)
# Genes altamanete expresados: PCSK1, SH2B1, LFPR, ADCY3, ANO4, POMC en ciertos pacientes de datos crudos 
# Pero la mayoria de genes no tienen un nivel alto de expresion 

```

```{r}

# ------------------------------------------------------------------
# Terciles para PCs
# ------------------------------------------------------------------

# Puntos de corte
corte <- function(x){
  cut(
    x,
    breaks = quantile(x, probs = c(0, 1/3, 2/3, 1), na.rm = TRUE),
    include.lowest = TRUE,
    labels = c("T1", "T2", "T3")
  )
}

# Asignar los cortes a columnas de PCs en df
df$PC1_t <- corte(df$PC1)
df$PC2_t <- corte(df$PC2)
df$PC3_t <- corte(df$PC3)

# ------------------------------------------------------------------
# Tabla descriptiva
# ------------------------------------------------------------------

# PC1

tabla_PC1 <- df %>%
  select(PC1_t, all_of(genes_interes)) %>%
  tbl_summary(
    by = PC1_t,
    type = list(
      all_of(genes_interes) ~ "continuous"
    ),
    statistic = all_continuous() ~ "{median} ({p25}–{p75})",
    digits = all_continuous() ~ 1,
  ) %>%
  add_p(
    test = list(all_of(genes_interes) ~ "kruskal.test"),
    pvalue_fun = ~ style_pvalue(.x, digits = 3)
  ) %>%
  # Mejorar formato
  modify_header(
    label = "**Gen**",
    stat_1 = "**T1** (N = {n})",
    stat_2 = "**T2** (N = {n})",
    stat_3 = "**T3** (N = {n})"
  )

# PC2

tabla_PC2 <- df %>%
  select(PC2_t, all_of(genes_interes)) %>%
  tbl_summary(
    by = PC2_t,
    type = list(
      all_of(genes_interes) ~ "continuous"
    ),
    statistic = all_continuous() ~ "{median} ({p25}–{p75})",
    digits = all_continuous() ~ 1,
  ) %>%
  add_p(
    test = list(all_of(genes_interes) ~ "kruskal.test"),
    pvalue_fun = ~ style_pvalue(.x, digits = 3)
  ) %>%
  # Mejorar formato
  modify_header(
    label = "**Gen**",
    stat_1 = "**T1** (N = {n})",
    stat_2 = "**T2** (N = {n})",
    stat_3 = "**T3** (N = {n})"
  )

# PC3

tabla_PC3 <- df %>%
  select(PC3_t, all_of(genes_interes)) %>%
  tbl_summary(
    by = PC3_t,
    type = list(
      all_of(genes_interes) ~ "continuous"
    ),
    statistic = all_continuous() ~ "{median} ({p25}–{p75})",
    digits = all_continuous() ~ 1,
  ) %>%
  add_p(
    test = list(all_of(genes_interes) ~ "kruskal.test"),
    pvalue_fun = ~ style_pvalue(.x, digits = 3)
  ) %>%
  # Mejorar formato
  modify_header(
    label = "**Gen**",
    stat_1 = "**T1** (N = {n})",
    stat_2 = "**T2** (N = {n})",
    stat_3 = "**T3** (N = {n})"
  )

# Unir todas las tablas 

# Unir las tablas
tabla_combinada <- tbl_merge(
  tbls = list(tabla_PC1, tabla_PC2, tabla_PC3),
  tab_spanner = c("**Componente 1**", "**Componente 2**", "**Componente 3**")
)

# Mostrar tabla combinada
tabla_combinada

```


```{r, warning=FALSE}
# ------------------------------------------------------------------
# 7.REGRESIÓN LOGÍSTICA
# --------------------------------------------------- ---------------
# Crear los terciles usando los valores en el df
df <- df %>%
  mutate(
    # Variable de respuesta: Obesidad (variable categórica a partir de 'categoria_imc')
    obesidad = factor(ifelse(categoria_imc == "Obesidad", "Si", "No"), 
                      levels = c("No", "Si")),
    obesidad = relevel(obesidad, ref = "No"),
    
    # Crear los terciles a partir de las columnas PC1, PC2... que se añadieron al df
    PC1_t = cut(PC1, breaks = quantile(PC1, probs = seq(0, 1, 1/3)), 
                labels = c("t1", "t2", "t3"), include.lowest = TRUE),
    PC2_t = cut(PC2, breaks = quantile(PC2, probs = seq(0, 1, 1/3)), 
                labels = c("t1", "t2", "t3"), include.lowest = TRUE),
    PC3_t = cut(PC3, breaks = quantile(PC3, probs = seq(0, 1, 1/3)), 
                labels = c("t1", "t2", "t3"), include.lowest = TRUE)
  )

# Ejecutar el modelo logístico
modelo1_log <- glm(
  obesidad ~ PC1_t + PC2_t + PC3_t + edad_anios + sexo + tabaco + glucosa_mg_dl + alcohol,  
  data = df,
  family = binomial
)

modelo2_log <- glm(obesidad ~ PC1_t + PC2_t + PC3_t + edad_anios + sexo + tabaco + alcohol + glucosa_mg_dl + ldl_mg_dl,
  data = df,
  family = binomial
)

modelo3_log <- glm(obesidad ~ PC1_t + PC2_t + PC3_t + edad_anios + sexo + tabaco,
  data = df,
  family = binomial
) 


summary(modelo1_log)
summary(modelo2_log)
summary(modelo3_log)

#Ver el AIC directamente
modelo1_log$aic
modelo2_log$aic
modelo3_log$aic


#MODELOS 1, 2, 3 
tbl1 <- tbl_regression(modelo1_log, exponentiate = TRUE) 
tbl2 <- tbl_regression(modelo2_log, exponentiate = TRUE)
tbl3 <- tbl_regression(modelo3_log, exponentiate = TRUE)

tabla_logit <- tbl_merge(
  tbls = list(tbl1, tbl2, tbl3),
  tab_spanner = c("M1: PC1-PC3 + edad_anios + sexo + tabaco +   glucosa_mg_dl + alcohol",
                  "M2: PC1-PC3 + edad_anios + sexo + tabaco + alcohol + glucosa_mg_dl + ldl_mg_dl",
                  "M3: PC1-PC3 + edad_anios + sexo + tabaco")
) %>% bold_labels()

tabla_logit


# EVALUACIÓN DEL MODELO 3. Mejor capacidad predictiva
# Obtener predicciones 
predicciones <- predict(modelo3_log, type = "response" )

# Calcular la curva ROC
roc_obj <- roc(df$obesidad, predicciones)

# Graficar
plot(roc_obj, main = paste("Modelo3_Curva ROC - AUC:", round(auc(roc_obj), 2)), col = "blue")
```

INTERPRETACIÓN: 
